### ISSUE TITLE
Random user names have a non-random prefix?

### ISSUE THREAD

**Issue by ltique** [SkipLabs/skip#109]
It seems that `--create-user` creates users with a non-random prefix:

```
$ npx skdb --dev --create-user --db chat-app
Successfully created user:  {
  f7rXJgr_UkpaoGDYUuM0c3b8Sz2: '...'
}
$ npx skdb --dev --create-user --db chat-app
Successfully created user:  {
  f7rXKWj0XQN155xsrF0PgSSwqN0: '...'
}
$ npx skdb --dev --create-user --db chat-app
Successfully created user:  {
  f7rXW0KTJrjfjya0cCRZNFZ3Ht3: '...'
}
```

There might be a good reason for this, and it isn't a security issue, but it makes it quite hard as a human to differentiate one username from another: you have to skip the first 4 characters ("f7rX") before getting to the actually random part.

**Comment by jberdine** [comment]
They start with a 32-bit timestamp in seconds since 2014-05-13T16:53:20.000Z.

**Comment by ltique** [comment]
Ah, right, so they're a pretty printed UUID I guess? Hmm, then the implied ordering that starting with the timestamp gives is useful in other areas I suppose?

**Comment by jberdine** [comment]
See [source](https://github.com/SkipLabs/skdb/blob/main/prelude/src/stdlib/other/Ksuid.sk#L1-L12) for more detail.

**Comment by ltique** [comment]
Thanks!

**Comment by jberdine** [comment]
Yes, they sort in roughly the order in which they are constructed, which is potentially good for locality of reference of data structures, etc.
