### ISSUE TITLE
Questions: Mirroring "sophistication", Concurrent writes, React Native etc...

### ISSUE THREAD

**Issue by MirjamElad** [SkipLabs/skip#128]
Hello and thank you for this exciting software.
I ve stumbled upon SKDB few days back and I cannot stop thinking about it. 
Many questions popping up in my head. Let me try and spell them down here:

 Take the code below:
```
await skdb.mirror(
    {
      table: "chess_moves",
      filterExpr: "game_state = 'started'"
    }
  );
```
1- What are the limits of what **`filterExpr`** can "express"? Can one use **any** SQL expression to pick what rows and columns to sync from the **chess_moves** table? Can the filtering part of the expression use multiple different tables (other than **chess_moves** ) at once  (exp using joins ... etc)? 

3- I am guessing SKDB is uses WASM & the upcoming OPFS to work on the browser (and not Persist through IndexedDB ...etc). Also, since it runs in the user's device, it needs not catter to concurent writes (same as SQLite). However, SKDB runs also on the Server. How does that work? Is it the exact same version on both Browser and Server? Does that mean SKDB on the server is not meant to handle large ammounts of concurent writes? any **benchmarks**? BTW: Electric-SQL for instance uses PostgreSQL on the server!

4- Since it relies on WASM, why not having it work in React Native? Maybe it's already done or planned?

5- How about the software licenses. In Browser, Server and React NAtive? Any possibly other options you have in the pipeline.

I would appreciate much if you could give me some feedback on the above.
Best wishes!

**Comment by MirjamElad** [comment]
One more important question:

6- Can we subscribe to the SKDB changes on the server as well as the browser? Say I want to send a welcome email to any new user entering her email. So the SKDB in the browser gets updated with the email and through `skdb.mirror` the SKDB instance on the server gets updated as well. Can one also use `skdb.watch` on the server to react to this same event and send an email by invoking -say- sendgrid API? .. It's almost midnight here in Europe. I hope I am still making sense :). Any code samples on how to best react to SKDB changes in both the Browser and the Server? ... How about React Native

**Comment by gregsexton** [comment]
1. You can use any sql expression to select rows from the table. Mirroring happens at the grain of a table so you cannot use a join here. But you can define reactive views on the server side that use a join and mirror these. Then you could supply a filter over the joined tables.
2. There doesn't seem to be a 2. :D 
3. It uses WASM. We may consider using OPFS. Currently we aren't focused on persistence in the browser as it's very limited. It is the same software in the browser or backend. We compile to wasm for the browser and to a native binary for the backend. SKDB is designed to support high concurrency. The expected use case is many simultaneous users connected to the same server synchronising data.
4. React Native is possible. We plan to make SKDB available everywhere: iOS, android, backend jvm services, python, etc etc.
5. The software is MIT licensed.
6. Of course! The idea is to build reactive systems end to end. You can run skdb in the browser that mirrors a table and watches an SQL query. This can be used e.g. to update the rendered view. You can do exactly the same thing in backend services: mirror the table, watch a query, and use this to do anything you like. You could send an email, interact with another service, etc. The backend can write to tables to communicate to other backend services or users.  Today the best supported way to build backends is to use Node.js but we're working on other ecosystems.

**Comment by gregsexton** [comment]
I hope this answers your questions. I'm going to close this. But feel free to join our discord channel if you have more questions. :)
