### ISSUE TITLE
Auth errors when creating multiple dev users at the CLI.

### ISSUE THREAD

**Issue by bennostein** [SkipLabs/skip#15]
Repro:

1. run a devserver with `docker run -it -p 3586:8080 skiplabs/skdb-dev-server:quickstart`
2. `npx skdb --create-user alice --db repro --dev` runs successfully, outputs credentials to stdout
3. `npx skdb --create-user bob --db repro --dev` fails with the following:
```
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^
Authorization error
Thrown at:
    at loadESM (node:internal/process/esm_loader:48:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


Node.js v20.7.0
```

**Comment by gregsexton** [comment]
You need to connect as root to create users. I suspect that, when not supplied, you connect as the first user in the map. Which is possibly alice? Try passing --user explicitly.

**Comment by gregsexton** [comment]
This is probably a restriction we can lift for the dev server?

**Comment by bennostein** [comment]
> You need to connect as root to create users. I suspect that, when not supplied, you connect as the first user in the map. Which is possibly alice? Try passing --user explicitly.

Yep, that's exactly it, I can create multiple users if I pass `--access-key root`.  Thanks!  I'll see about lifting that restriction.
