### ISSUE TITLE
Is this project open source?

### ISSUE THREAD

**Issue by josephrocca** [SkipLabs/skip#194]
Hi, I just saw this project mentioned in a tweet, so I don't have a lot of context. There's no license in the README which often indicates that the project doesn't intend to be open source. That's fine of course - each project needs to decide that for themselves based on their business model and/or other factors.

That said, if this project *is* in fact open source, then it'd definitely be a good idea to add a license. At the very least it'd help you get a few extra stars from people like me who need to reduce the chance of lock-in risk for critical parts of their infrastructure, even if using the company's associated cloud offerings.

Please feel free to close, of course, if the project isn't ready for a license, for whatever reason.

**Comment by gregsexton** [comment]
The project is intended to be released under the MIT licence. Thanks for pointing out that we're missing the necessary files. We'll fix this.
