### ISSUE TITLE
what's the benefit of using a `TimeQueue` vs an array of `Timeout`s created using JS's `setInterval()`?

### ISSUE THREAD

**Issue by mbouaziz** [SkipLabs/skip#352]
Unrelated to this PR: what's the benefit of using a `TimeQueue` vs an array of `Timeout`s created using JS's `setInterval()`?

_Originally posted by @beauby in https://github.com/SkipLabs/skdb/pull/350#pullrequestreview-2339791613_

**Comment by beauby** [comment]
Closed by #356.
