### ISSUE TITLE
[skipruntime/client] `subscribe()` should not explicitly take a `watermark` parameter.

### ISSUE THREAD

**Issue by beauby** [SkipLabs/skip#384]
Tangential to this PR, but this makes me think that deconstruction of the `Reactive-Response-Token` should happen within the skip client, and the token itself be passed transparently through to `subscribe()`, instead of `subscribe()` taking a collection name + watermark. Just something to keep in mind, no action required on your end in this PR.

_Originally posted by @beauby in https://github.com/SkipLabs/skdb/pull/382#discussion_r1793447433_

**Comment by bennostein** [comment]
Done, #467
