### ISSUE TITLE
Consider renaming the Constant type, and relationship with Param

### ISSUE THREAD

**Issue by jberdine** [SkipLabs/skip#578]
Documenting the Constant type indicated that it is misnamed, as some inhabitants are in fact non-constant, it is just that their modifications can be tracked by skip.

Additionally, there is little conceptual difference for users between Constant and Param. It seems likely that unifying them in the exposed interface would be an improvement.

**Comment by bennostein** [comment]
Support on both fronts!  I've thought about this for a while but haven't been able to come up with a good name for this type, though...

**Comment by jberdine** [comment]
Also, `NonEmptyIterator` should be renamed to some plural form of whatever `Constant` and `Param` get renamed to. See also https://github.com/SkipLabs/skip/pull/582#discussion_r1876054925.
