### ISSUE TITLE
Audit/confirm type of LazyCompute.compute

### ISSUE THREAD

**Issue by jberdine** [SkipLabs/skip#607]
The type of `LazyCompute.compute` is declared as `compute(self: LazyCollection<K, V>, key: K): Nullable<V>` in api.ts. It is not clear why the return type is `Nullable<V>`, I expected `Array<V>`. Perhaps I have gotten lost in the cross-lang interop, but it seems that `createLazyCollection` calls `createLazyCompute` which returns an `ExternLazyCompute` whose `compute` is defined as
```
  fun compute(self: LazyCollection, key: SKJSON.CJSON): Array<SKJSON.CJSON> {
    computeOfLazyCompute(this.eptr.value, self.getId(), key) match {
    | SKJSON.CJArray(value) -> value
    | _ -> invariant_violation("Invalid computed value.")
    }
  }
```
This seems more in line with returning an array than a nullable.

**Comment by bennostein** [comment]
I agree with your read of things -- we should probably give LazyCompute.compute an `Iterable<V>` return type like eager mappers have.  Maybe with a specialized version returning just the one `V`, à la `OneToOneMapper`

@skiplabsdaniel what do you think?
