### ISSUE TITLE
[skdb] Creating an SKDB instance as a worker causes JS to hang

### ISSUE THREAD

**Issue by gregsexton** [SkipLabs/skip#96]
Repro:
```
import { createSkdb } from "skdb";
const db = await createSkdb({ asWorker: true });
```

If you change asWorker to false the node process will exit cleanly, otherwise it hangs.

The skdb type has a closeConnection method. We should probably change this to close() which should close any conns, other resources, and the worker if needed.

**Comment by gregsexton** [comment]
This is a low hanging one if someone fancies a quick win.

**Comment by beauby** [comment]
Closing skdb-specific issues as skdb in its current form is being deprecated.
